const WHATSAPP_NUMBER="966500000000"; // رقم تجريبي حتى ترسل رقم المتجر الحقيقي
const products=[
{id:1,cat:"oil",name:"زيت زيتون بكر ممتاز",desc:"عبوة 1 لتر – عصر على البارد",price:65,oldPrice:72,icon:"🫒",badge:"الأكثر طلباً",rating:4.9,reviews:28,purchases:86,stock:14,benefit:"مصدر للدهون الأحادية غير المشبعة ومناسب للسلطات والطهي المعتدل ضمن نظام غذائي متوازن.",use:"السلطات، الزعتر، التتبيل والطهي المعتدل.",storage:"يحفظ في مكان بارد ومظلم بعيداً عن الحرارة والضوء.",specs:["النوع: بكر ممتاز","السعة: 1 لتر","الاستخدام: يومي","التعبئة: عبوة محكمة"]},
{id:2,cat:"oil",name:"زيت زيتون عائلي",desc:"جالون 4 لتر – للاستخدام العائلي",price:225,oldPrice:245,icon:"🫙",badge:"توفير",rating:4.8,reviews:19,purchases:61,stock:8,benefit:"خيار اقتصادي للعائلات التي تستخدم زيت الزيتون بشكل يومي.",use:"الطبخ والتتبيل والسلطات.",storage:"بعيداً عن الشمس والحرارة مع إغلاق العبوة جيداً.",specs:["النوع: زيت زيتون","السعة: 4 لتر","الحجم: عائلي","التخزين: مكان مظلم"]},
{id:3,cat:"ghee",name:"سمنة عربية فاخرة",desc:"عبوة 500 غرام",price:48,oldPrice:null,icon:"🥣",badge:"طعم أصيل",rating:4.8,reviews:17,purchases:47,stock:20,benefit:"مصدر مركز للطاقة ونكهتها غنية، لذلك غالباً كمية صغيرة تكفي.",use:"الأرز، الحلويات، المعجنات والأطباق الشامية.",storage:"استخدم ملعقة نظيفة وجافة واحفظ وفق تعليمات العبوة.",specs:["السعة: 500 غ","الطعم: غني","الاستخدام: طبخ وحلويات","العبوة: محكمة"]},
{id:4,cat:"ghee",name:"سمنة عربية عائلية",desc:"عبوة 1 كيلو",price:88,oldPrice:95,icon:"🍯",badge:"عائلي",rating:4.9,reviews:23,purchases:58,stock:11,benefit:"مناسبة للاستخدام المنزلي بكمية أكبر مع نكهة تقليدية مركزة.",use:"الأرز، المقلوبة، الحلويات والطبخ.",storage:"تحفظ بعيداً عن الرطوبة والحرارة بحسب تعليمات العبوة.",specs:["السعة: 1 كغ","الاستخدام: عائلي","القوام: غني","التخزين: جاف وبارد"]},
{id:5,cat:"pomegranate",name:"دبس رمان طبيعي",desc:"زجاجة 500 مل – نكهة مركزة",price:29,oldPrice:null,icon:"🍷",badge:"طبيعي",rating:4.7,reviews:14,purchases:44,stock:26,benefit:"يعطي حموضة ونكهة مركزة للتتبيلات؛ محتوى السكر يعتمد على التصنيع.",use:"الفتوش، التبولة، المشاوي والتتبيلات.",storage:"اتبع تعليمات الملصق ويفضل إغلاق العبوة جيداً بعد الفتح.",specs:["السعة: 500 مل","النكهة: حامضة مركزة","الاستخدام: تتبيل","القوام: كثيف"]},
{id:6,cat:"pomegranate",name:"دبس رمان مركز",desc:"زجاجة 1 لتر",price:52,oldPrice:58,icon:"🍎",badge:"للمطاعم",rating:4.8,reviews:16,purchases:39,stock:13,benefit:"حجم أكبر للمطابخ التي تستخدم دبس الرمان بكثرة.",use:"الصلصات، التتبيل، المحاشي والمشاوي.",storage:"يحفظ وفق تعليمات العبوة بعد الفتح.",specs:["السعة: 1 لتر","التركيز: مرتفع","الاستخدام: منزلي ومطاعم","التعبئة: زجاجة"]},
{id:7,cat:"soap",name:"صابون غار حلبي",desc:"قطعة 180 غرام تقريباً",price:14,oldPrice:null,icon:"🧼",badge:"تقليدي",rating:4.8,reviews:31,purchases:103,stock:40,benefit:"صابون تقليدي للتنظيف اليومي. للبشرة الحساسة يفضل الاختبار على مساحة صغيرة أولاً.",use:"لليدين والجسم حسب ملاءمته لنوع البشرة.",storage:"يترك ليجف بين الاستخدامات على حامل جيد التصريف.",specs:["الوزن: نحو 180 غ","النوع: صابون تقليدي","الاستخدام: تنظيف يومي","الحفظ: مكان جاف"]},
{id:8,cat:"soap",name:"باقة صابون غار",desc:"6 قطع بتغليف هدية",price:72,oldPrice:84,icon:"🎁",badge:"هدية",rating:4.9,reviews:22,purchases:54,stock:9,benefit:"باقة عملية للاستخدام العائلي أو كهدية.",use:"تنظيف يومي حسب ملاءمة البشرة.",storage:"احفظ القطع غير المستخدمة في مكان جاف.",specs:["العدد: 6 قطع","التغليف: هدية","الاستخدام: عائلي","الحفظ: جاف"]}
];
const customerReviews=[
{name:"سارة",text:"التغليف مرتب والطلب كان واضح من أول خطوة.",stars:5},
{name:"محمد",text:"حبيت وجود تفاصيل الاستخدام والتخزين مع كل منتج.",stars:5},
{name:"ريم",text:"السلة سهلة، وأكثر شي عجبني اقتراح المنتجات المشابهة.",stars:5},
{name:"أبو خالد",text:"تجربة مرتبة وسريعة، وبانتظار إضافة صور المنتجات الحقيقية.",stars:4},
{name:"هدى",text:"الشرح مفيد خصوصاً للفرق بين الأحجام والاستخدام.",stars:5},
{name:"نادر",text:"واجهة بسيطة وواضحة على الجوال.",stars:5}
];
let cart=JSON.parse(localStorage.getItem("oliveCart")||"{}");
const grid=document.getElementById("productGrid"),bestGrid=document.getElementById("bestGrid"),cartEl=document.getElementById("cart"),overlay=document.getElementById("overlay"),modal=document.getElementById("productModal");
function money(n){return n+" ر.س"}
function card(p){return `<article class="product-card"><div class="product-image" onclick="openProduct(${p.id})"><span class="product-badge">${p.badge}</span><button class="wish" onclick="event.stopPropagation();toggleWish(this)">♡</button>${p.icon}</div><div class="product-info"><div class="stars">★★★★★ <small>${p.rating} (${p.reviews})</small></div><h3 onclick="openProduct(${p.id})">${p.name}</h3><p>${p.desc}</p><div class="price-line"><span class="price">${money(p.price)}</span>${p.oldPrice?`<span class="old-price">${money(p.oldPrice)}</span>`:""}</div><div class="product-actions"><button class="details-btn" onclick="openProduct(${p.id})">عرض التفاصيل</button><button class="add" onclick="addToCart(${p.id})">+</button></div><div class="purchase-note">تم طلبه ${p.purchases} مرة • المتبقي ${p.stock}</div></div></article>`}
function renderProducts(filter="all",query=""){let list=products.filter(p=>(filter==="all"||p.cat===filter)&&(!query||(`${p.name} ${p.desc}`).includes(query)));grid.innerHTML=list.length?list.map(card).join(""):'<div class="empty">ما لقينا منتج مطابق للبحث.</div>'}
function renderBest(){bestGrid.innerHTML=[...products].sort((a,b)=>b.purchases-a.purchases).slice(0,4).map(card).join("")}
function renderReviews(){document.getElementById("reviewsGrid").innerHTML=customerReviews.map(r=>`<article class="review-card"><div class="review-head"><div class="avatar">${r.name[0]}</div><span class="stars">${"★".repeat(r.stars)}${"☆".repeat(5-r.stars)}</span></div><b>${r.name}</b><p>${r.text}</p><span class="verified">✓ مراجعة تجريبية</span></article>`).join("")}
function toggleWish(btn){btn.textContent=btn.textContent==="♡"?"♥":"♡"}
function addToCart(id,open=true){cart[id]=(cart[id]||0)+1;save();if(open)openCart()}
function changeQty(id,d){cart[id]=(cart[id]||0)+d;if(cart[id]<=0)delete cart[id];save()}
function save(){localStorage.setItem("oliveCart",JSON.stringify(cart));renderCart()}
function renderCart(){const entries=Object.entries(cart);document.getElementById("cartCount").textContent=entries.reduce((s,[,q])=>s+q,0);if(!entries.length){document.getElementById("cartItems").innerHTML='<div class="empty">سلتك فارغة حالياً 🫒</div>';document.getElementById("cartTotal").textContent="0 ر.س";return}let total=0;document.getElementById("cartItems").innerHTML=entries.map(([id,q])=>{const p=products.find(x=>x.id==id);total+=p.price*q;return `<div class="cart-item"><div class="cart-icon">${p.icon}</div><div><h4>${p.name}</h4><small>${money(p.price)} × ${q}</small></div><div class="qty"><button onclick="changeQty(${p.id},-1)">−</button><b>${q}</b><button onclick="changeQty(${p.id},1)">+</button></div></div>`}).join("");document.getElementById("cartTotal").textContent=money(total)}
function openCart(){cartEl.classList.add("open");overlay.classList.add("show")}
function closeCart(){cartEl.classList.remove("open");overlay.classList.remove("show")}
function similarFor(p){return products.filter(x=>x.id!==p.id&&x.cat===p.cat).slice(0,4)}
function suggestedFor(p){return products.filter(x=>x.id!==p.id&&x.cat!==p.cat).sort((a,b)=>b.rating-a.rating).slice(0,4)}
function likedFor(p){return products.filter(x=>x.id!==p.id).sort((a,b)=>b.purchases-a.purchases).slice(0,4)}
function mini(list){return list.map(x=>`<div class="mini-card" onclick="openProduct(${x.id})"><span>${x.icon}</span><b>${x.name}</b><small>${money(x.price)}</small></div>`).join("")}
function openProduct(id){const p=products.find(x=>x.id===id);if(!p)return;document.getElementById("modalContent").innerHTML=`<div class="product-detail"><div class="detail-top"><div class="detail-visual">${p.icon}</div><div class="detail-info"><div class="breadcrumbs">الرئيسية / المنتجات / ${p.name}</div><div class="stars">★★★★★ <small>${p.rating} من 5 • ${p.reviews} تقييم</small></div><h1>${p.name}</h1><p class="detail-desc">${p.desc}. ${p.benefit}</p><div class="detail-price"><span class="price">${money(p.price)}</span>${p.oldPrice?`<span class="old-price">${money(p.oldPrice)}</span>`:""}</div><span class="stock">متوفر • المتبقي ${p.stock}</span><div class="purchase-note">تم طلب هذا المنتج ${p.purchases} مرة</div><div class="detail-actions"><button class="buy-now" onclick="addToCart(${p.id});closeProduct()">أضف للسلة</button><button class="add-detail" onclick="consultProduct(${p.id})">اسأل عن المنتج</button></div><div class="modal-note">المعلومات الصحية هنا عامة للتثقيف وليست علاجاً أو استشارة طبية.</div></div></div>
<div class="info-tabs"><div class="info-box"><h3>المواصفات</h3><ul>${p.specs.map(x=>`<li>${x}</li>`).join("")}</ul></div><div class="info-box"><h3>طريقة الاستخدام</h3><p>${p.use}</p></div><div class="info-box"><h3>الحفظ</h3><p>${p.storage}</p></div></div>
<section class="recommend-section"><h2>منتجات مشابهة</h2><div class="recommend-grid">${mini(similarFor(p))}</div></section>
<section class="recommend-section"><h2>منتجات قد تعجبك</h2><div class="recommend-grid">${mini(suggestedFor(p))}</div></section>
<section class="recommend-section"><h2>منتجات حازت على إعجاب العملاء</h2><div class="recommend-grid">${mini(likedFor(p))}</div></section>
<section class="product-reviews"><h2>آراء العملاء عن هذا النوع</h2>${customerReviews.slice(0,3).map(r=>`<article class="review-card"><div class="review-head"><b>${r.name}</b><span class="stars">${"★".repeat(r.stars)}</span></div><p>${r.text}</p></article>`).join("")}</section>
<section class="product-faq"><h2>أسئلة شائعة</h2><div class="faq-list"><details><summary>هل المنتج متوفر حالياً؟</summary><p>نعم حسب المخزون الظاهر، ويتم تأكيد التوفر النهائي عند إرسال الطلب.</p></details><details><summary>كيف أعرف إذا هذا الحجم مناسب لي؟</summary><p>يمكنك طلب استشارة مجانية عن الاستخدام والحجم قبل الشراء.</p></details></div></section></div>`;modal.classList.add("open");modal.setAttribute("aria-hidden","false");document.body.style.overflow="hidden";modal.scrollTop=0}
function closeProduct(){modal.classList.remove("open");modal.setAttribute("aria-hidden","true");document.body.style.overflow=""}
function consultProduct(id){const p=products.find(x=>x.id===id);window.open(`https://wa.me/${WHATSAPP_NUMBER}?text=${encodeURIComponent("مرحباً، عندي استفسار عن: "+p.name+" - "+p.desc)}`,"_blank")}
function whatsappOrder(){const entries=Object.entries(cart);if(!entries.length){alert("أضف منتجاً للسلة أولاً");return}let total=0;const lines=entries.map(([id,q])=>{const p=products.find(x=>x.id==id);total+=p.price*q;return `• ${p.name} × ${q} = ${money(p.price*q)}`});const text=`مرحباً، أرغب بطلب:\n\n${lines.join("\n")}\n\nالإجمالي: ${money(total)}\n\nالاسم:\nالمدينة:\nالعنوان:`;window.open(`https://wa.me/${WHATSAPP_NUMBER}?text=${encodeURIComponent(text)}`,"_blank")}
document.querySelectorAll("#filters button").forEach(btn=>btn.onclick=()=>{document.querySelectorAll("#filters button").forEach(b=>b.classList.remove("active"));btn.classList.add("active");renderProducts(btn.dataset.filter);document.querySelector("#products").scrollIntoView()});
document.querySelectorAll(".category-card").forEach(btn=>btn.onclick=()=>{const f=document.querySelector(`#filters button[data-filter="${btn.dataset.cat}"]`);f.click()});
document.getElementById("cartBtn").onclick=openCart;document.getElementById("closeCart").onclick=closeCart;overlay.onclick=closeCart;document.getElementById("checkoutBtn").onclick=whatsappOrder;document.getElementById("clearCart").onclick=()=>{cart={};save()};
document.getElementById("menuBtn").onclick=()=>document.getElementById("navLinks").classList.toggle("open");
document.querySelectorAll(".links a").forEach(a=>a.onclick=()=>document.getElementById("navLinks").classList.remove("open"));
document.getElementById("searchBtn").onclick=()=>{document.getElementById("searchPanel").classList.toggle("open");document.getElementById("searchInput").focus()};
document.getElementById("closeSearch").onclick=()=>document.getElementById("searchPanel").classList.remove("open");
document.getElementById("searchInput").oninput=e=>{renderProducts("all",e.target.value.trim());document.querySelector("#products").scrollIntoView()};
document.getElementById("modalClose").onclick=closeProduct;modal.onclick=e=>{if(e.target===modal)closeProduct()};document.addEventListener("keydown",e=>{if(e.key==="Escape")closeProduct()});
document.getElementById("consultBtn").onclick=()=>window.open(`https://wa.me/${WHATSAPP_NUMBER}?text=${encodeURIComponent("مرحباً، أريد استشارة مجانية عن اختيار واستخدام المنتجات.")}`,"_blank");
document.getElementById("year").textContent=new Date().getFullYear();renderProducts();renderBest();renderReviews();renderCart();